[build]
  base = "examples/docs/"
  functions = "functions/"
  publish = "dist/"
  command = "export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && (cd ../../ && npm install --no-optional && npx --no-install elm-tooling install) && npm install --no-optional && npm run build && cp ./elm-stuff/elm-pages/elm.js functions/render/elm-pages-cli.js"
  ignore = "git diff --quiet HEAD^ HEAD `git rev-parse --show-toplevel`"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
  # force = true
