[build]
  base = "examples/docs/"
  publish = "dist/"
  command = "export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && (cd ../../ && npm install && npx --no-install elm-tooling install) && npm install && npm run build"
  ignore = "git diff --quiet HEAD^ HEAD `git rev-parse --show-toplevel`"
